def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}

def appImage

pipeline {
    agent any

    // Tarea 6.4: Definición de variables globales
    environment {
        IMAGE_NAME = "contrerasadr/devops-training-python-app:${env.BUILD_NUMBER}"
        APP_URL    = "http://localhost:5001/"
    }
    
    parameters {
        booleanParam(name: 'RUN_CD', defaultValue: false, description: 'Ejecutar CD manualmente')
    }

    stages {
        stage('Build CI Image') {
            steps {
                sh 'docker build -t mi-app-ci -f devops/ci.Dockerfile .'
            }
        }
        
        stage('Lint') {
            steps {
                script {
                    runInDocker('mi-app-ci') {
                        sh 'make lint'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    runInDocker('mi-app-ci') {
                        sh 'make test'
                    }
                }
            }
        }

        stage('Build Image') {
            steps {
                script {
                    echo "Construyendo imagen: ${env.IMAGE_NAME}"
                    // Usamos la variable de entorno para el tag de la imagen
                    appImage = docker.build("${env.IMAGE_NAME}", "-f Dockerfile .")
                }
            }
        }
        
        stage('CD') {
            when {
                anyOf {
                    expression { return params.RUN_CD }
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                script {
                    env.DEPLOY_ENV = (env.BRANCH_NAME == 'master') ? 'PRO' : 'DEV'
                    def projectName = env.DEPLOY_ENV.toLowerCase()
                    
                    echo "CD habilitado: RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"
                    echo "Deploying to ${env.DEPLOY_ENV}"
                    echo "URL de la App: ${env.APP_URL}"
                    
                    try {
                        // Limpieza para evitar conflictos previos
                        sh "docker rm -f my-flask-app-db my-flask-app-dc || true"
                        sh "docker compose -p ${projectName} down --volumes --remove-orphans"
                        
                        // Inyectamos la variable IMAGE_NAME para que Compose sepa qué imagen usar
                        withEnv(["IMAGE_NAME=${env.IMAGE_NAME}"]) {
                            sh "docker compose -p ${projectName} up -d"
                        }
                        
                        sleep 5
                        sh "docker compose -p ${projectName} logs app"
                        
                    } finally {
                        sh "docker compose -p ${projectName} down --volumes --remove-orphans"
                    }
                }
            }
        }
    }
}
